version: '3.4'

services:
  web:
    container_name: web
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    expose:
      - "8000"
    volumes:
      - .:/app
    networks:
      - blog_nw

volumes:
  data:

networks:
  blog_nw:
    driver: bridge
